LogisticRegression:
  penalty: ['l1', 'l2']
  C: [0.001, 0.01, 0.1, 1, 10, 100, 1000]
  max_iter: [100, 200, 300, 400, 500, 900]

KNearest:
  n_neighbors: [2, 3, 4]
  algorithm: ['auto', 'ball_tree', 'kd_tree', 'brute']

SupportVectorClassifier:
  C: [0.5, 0.7, 0.9, 1]
  kernel: ['rbf', 'poly', 'sigmoid', 'linear']

DecisionTreeClassifier:
  criterion: ['gini', 'entropy']
  max_depth: [2, 3]
  min_samples_leaf: [5, 6]


# RandomForestClassifier:
#   n_estimators: [100, 200, 300]
#   criterion: ['gini', 'entropy']
#   max_depth: [None, 10, 20]
#   min_samples_split: [2, 5, 10]