artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Godwin45/FraudApp/raw/main/creditcard.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_cleaning:
  root_dir: artifacts/data_cleaning
  unzip_data_dir: artifacts/data_ingestion/creditcard.csv
  cleaned_data: artifacts/data_cleaned/new_df.csv

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_cleaning/new_df.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_cleaning/new_df.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: best_model.joblib 

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/best_model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json